
package com.travelaround.view;

public class BookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingForm.class.getName());
    private com.travelaround.controller.BookingController bookingController;
    private com.travelaround.model.User currentUser;

    /**
     * Creates new form BookingForm tracked to active session
     */
    public BookingForm(com.travelaround.model.User user) {
        initComponents();
        this.currentUser = user;
        this.bookingController = new com.travelaround.controller.BookingController();
        this.setLocationRelativeTo(null); // Center form smoothly on launch
    }

    // Safe default fallback constructor
    public BookingForm() {
        initComponents();
        this.bookingController = new com.travelaround.controller.BookingController();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRoomId = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        tlblCheckIn = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        btnConfirmBooking = new javax.swing.JButton();
        txtRoomId = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        txtCheckIn = new javax.swing.JTextField();
        txtCheckOut = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblRoomId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRoomId.setText("Room ID :");

        lblTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalCost.setText("Total Price Field : ");

        tlblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tlblCheckIn.setText("Check-In Date Field :");

        lblCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckOut.setText("Check-Out Date Field :");

        btnConfirmBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmBooking.setText("Confirm");
        btnConfirmBooking.addActionListener(this::btnConfirmBookingActionPerformed);

        txtCheckIn.setText("YYYY-MM-DD");

        txtCheckOut.setText("YYYY-MM-DD");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Booking System");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblRoomId))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(lblTotalCost)
                                        .addGap(40, 40, 40))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tlblCheckIn)
                                            .addComponent(lblCheckOut))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(165, 165, 165))
                            .addComponent(btnConfirmBooking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomId)
                    .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlblCheckIn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckOut))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
        String roomIdStr = txtRoomId.getText().trim();
        String costStr = txtTotalCost.getText().trim();
        String checkIn = txtCheckIn.getText().trim();
        String checkOut = txtCheckOut.getText().trim();

        if (roomIdStr.isEmpty() || costStr.isEmpty() || checkIn.isEmpty() || checkOut.isEmpty() 
                || checkIn.equalsIgnoreCase("YYYY-MM-DD") || checkOut.equalsIgnoreCase("YYYY-MM-DD")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please supply all processing fields with valid data.");
            return;
        }

        // Validate date layout structures before processing transactions
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
        try {
            java.time.LocalDate.parse(checkIn, formatter);
            java.time.LocalDate.parse(checkOut, formatter);
        } catch (java.time.format.DateTimeParseException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Dates must match the exact layout requested (YYYY-MM-DD).", "Format Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int roomId = Integer.parseInt(roomIdStr);
            double cost = Double.parseDouble(costStr);
            
            // Derive active customer context dynamically or fall back to 1 safely
            int userId = (currentUser != null) ? currentUser.getUserId() : 1;
            
            // Execute structural database booking transactional workflow
            boolean success = bookingController.processRoomBooking(userId, roomId, checkIn, checkOut, cost);
            
            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Booking Transaction Confirmed! Invoice generated successfully.");
                btnClearActionPerformed(null); // Wipe fields clean on success
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Processing failed. Please check that Room ID exists and is available.", "Database Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid numerical entry parsed for Room ID or Total Price.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (com.travelaround.exception.RoomUnavailableException e) {
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Reservation Conflict Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose(); // Safely closes the booking window and leaves the dashboard open
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRoomId.setText("");
        txtTotalCost.setText("");
        txtCheckIn.setText("");
        txtCheckOut.setText("");    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblRoomId;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel tlblCheckIn;
    private javax.swing.JTextField txtCheckIn;
    private javax.swing.JTextField txtCheckOut;
    private javax.swing.JTextField txtRoomId;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
