/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.travelaround.view;

/**
 *
 * @author kevin
 */
public class BookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingForm.class.getName());

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRoomId = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTotalCost = new javax.swing.JLabel();
        tlblCheckIn = new javax.swing.JLabel();
        lblCheckOut = new javax.swing.JLabel();
        btnConfirmBooking = new javax.swing.JButton();
        txtRoomId = new javax.swing.JTextField();
        txtTotalCost = new javax.swing.JTextField();
        txtCheckIn = new javax.swing.JTextField();
        txtCheckOut = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRoomId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRoomId.setText("Room ID :");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("TravelAround Management Booking System");

        lblTotalCost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotalCost.setText("Total Price Field : ");

        tlblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tlblCheckIn.setText("Check-In Date Field :");

        lblCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCheckOut.setText("Check-Out Date Field :");

        btnConfirmBooking.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmBooking.setText("Confirm");
        btnConfirmBooking.addActionListener(this::btnConfirmBookingActionPerformed);

        txtCheckIn.setText("YYYY-MM-DD");

        txtCheckOut.setText("YYYY-MM-DD");

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(lblRoomId))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tlblCheckIn)
                                                .addComponent(lblCheckOut))
                                            .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(lblTotalCost)
                                            .addGap(40, 40, 40)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(102, 102, 102))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel1)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnClear)
                .addGap(88, 88, 88)
                .addComponent(btnConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRoomId)
                    .addComponent(txtRoomId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCost)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tlblCheckIn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheckOut))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBookingActionPerformed
    String roomIdStr = txtRoomId.getText().trim();
    String costStr = txtTotalCost.getText().trim();
    String checkIn = txtCheckIn.getText().trim();
    String checkOut = txtCheckOut.getText().trim();

    if (roomIdStr.isEmpty() || costStr.isEmpty() || checkIn.isEmpty() || checkOut.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please supply all processing fields.");
        return;
    }

    try {
        int roomId = Integer.parseInt(roomIdStr);
        double cost = Double.parseDouble(costStr);
        
        com.travelaround.controller.BookingController bookingController = new com.travelaround.controller.BookingController();
        
        // Try executing the database transaction operation
        boolean success = bookingController.processRoomBooking(1, roomId, checkIn, checkOut, cost); // Uses default user ID 1 for testing
        
        if (success) {
            javax.swing.JOptionPane.showMessageDialog(null, "Booking Transaction Confirmed! Invoice generated.");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Invalid numerical entry parsed.");
    } catch (com.travelaround.exception.RoomUnavailableException e) {
        // Catch and display your custom user-defined exception popup here
        javax.swing.JOptionPane.showMessageDialog(null, e.getMessage(), "Reservation Conflict Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnConfirmBookingActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose(); // Safely closes the booking window and leaves the dashboard open
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtRoomId.setText("");
        txtTotalCost.setText("");
        txtCheckIn.setText("");
        txtCheckOut.setText("");    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnConfirmBooking;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCheckOut;
    private javax.swing.JLabel lblRoomId;
    private javax.swing.JLabel lblTotalCost;
    private javax.swing.JLabel tlblCheckIn;
    private javax.swing.JTextField txtCheckIn;
    private javax.swing.JTextField txtCheckOut;
    private javax.swing.JTextField txtRoomId;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
