/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.travelaround.view;

/**
 *
 * @author kevin
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbluname = new javax.swing.JLabel();
        lblpwd = new javax.swing.JLabel();
        lblemail = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        btnSubmitRegister = new javax.swing.JButton();
        txtRegUsername = new javax.swing.JTextField();
        txtRegEmail = new javax.swing.JTextField();
        txtRegPhone = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClearFields = new javax.swing.JButton();
        txtRegPassword = new javax.swing.JPasswordField();
        btnBackToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbluname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbluname.setText("Username");

        lblpwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblpwd.setText("Password");

        lblemail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblemail.setText("Email");

        lblphone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblphone.setText("Phone");

        btnSubmitRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmitRegister.setText("Register");
        btnSubmitRegister.addActionListener(this::btnSubmitRegisterActionPerformed);

        txtRegPhone.addActionListener(this::txtRegPhoneActionPerformed);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Customer Registration Form");

        btnClearFields.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearFields.setText("Clear");
        btnClearFields.addActionListener(this::btnClearFieldsActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClearFields)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClearFields, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnBackToLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToLogin.setText("Back");
        btnBackToLogin.addActionListener(this::btnBackToLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbluname)
                                    .addComponent(lblpwd)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblphone)
                                    .addComponent(lblemail))))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRegPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtRegEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtRegUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(txtRegPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnBackToLogin)
                        .addGap(110, 110, 110)
                        .addComponent(btnSubmitRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluname)
                    .addComponent(txtRegUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpwd)
                    .addComponent(txtRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblemail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblphone))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToLogin))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
        this.dispose();
        com.travelaround.view.LoginForm loginWindow = new com.travelaround.view.LoginForm();
        loginWindow.setLocationRelativeTo(null);
        loginWindow.setVisible(true);
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        txtRegUsername.setText("");
        txtRegPassword.setText("");
        txtRegEmail.setText("");
        txtRegPhone.setText("");
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void btnSubmitRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRegisterActionPerformed
    String username = txtRegUsername.getText().trim();
    String password = new String(txtRegPassword.getPassword()).trim();
    String email = txtRegEmail.getText().trim();
    String phone = txtRegPhone.getText().trim();

    if (username.isEmpty() || password.isEmpty() || email.isEmpty() || phone.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "All fields are mandatory.", "Validation Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    com.travelaround.controller.UserController userController = new com.travelaround.controller.UserController();
    if (userController.registerCustomer(username, password, email, phone)) {
        javax.swing.JOptionPane.showMessageDialog(null, "Registration successful! You can now log in.");
        this.dispose();
        // Route back to the login gateway frame
        com.travelaround.view.LoginForm loginWindow = new com.travelaround.view.LoginForm();
        loginWindow.setLocationRelativeTo(null);
        loginWindow.setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Registration failed. Username might be taken.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSubmitRegisterActionPerformed

    private void txtRegPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegPhoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnSubmitRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblemail;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblpwd;
    private javax.swing.JLabel lbluname;
    private javax.swing.JTextField txtRegEmail;
    private javax.swing.JPasswordField txtRegPassword;
    private javax.swing.JTextField txtRegPhone;
    private javax.swing.JTextField txtRegUsername;
    // End of variables declaration//GEN-END:variables
}
